### ISSUE TITLE
Requests for featuers in old WIP PR from `substrate-docs`

### ISSUE THREAD

**Issue by NukeManDan** [paritytechmarcomms/substrate-docs-md#5]
See: https://github.com/substrate-developer-hub/substrate-docs/pull/732

---

**Objectives of this upgrade**
+ migrate from `.mdx` to `.md` with minimal losses in UX
+ create simple interface for contributors to add and maintain content
+ separating content maintenance and dev concerns
- [ ] versioning TBD

**Staging preview**
https://develop-docs-revamp--substrate-docs.netlify.app/quick-start/

### folder structure
Content is moved into folder: `./content/docs/`
- [x] added folder structure for `collections` (eg: main-docs), `topics` (eg: why-substrate): `./content/docs/<collection>/<topic>/:article.md`
- [x] remove indexing from folder names, order is provided by yaml config file in navigation

### slug generation
- [x] generating pages with `/path/slug/` based on `.md` file location
- [x] `./content/docs/<collection>/<topic>/:article.md` will be resolved as URL path `/collection/topic/article/`
- [x] collection pages: `./content/docs/<collection>/index.md` will be resolved as URL path `/collection/`
- [x] topic pages: `./content/docs/<collection>/<topic>/index.md` will be resolved as URL path `/collection/topic/`

### frontmatter
- [x] providing only necessary info in `.md` files:
```yaml
---
title: Markup Test page
keywords:
  - node
  - template
  - basics
---
```

### custom blocks
- [x] add simple custom blocks to `.md` markup: 
```
[[info]]
| This custom block uses **simple** `[[info]]` markup directly in vanilla markdown and renders as html
```
See here: https://develop-docs-revamp--substrate-docs.netlify.app/quick-start/#custom-blocks-feature

- [x] add possibility to use `<custom-components>`
```html
<custom-components data="arg">Content</custom-components>
```

### header and footer meta
- [ ] add last commit info on build time
- [ ] add header and footer UI (breadcrumbs, edit, repot issue, version, next, prev)

### Tutorials
- [x] tutorials page is generated only from content in `/docs/tutorials/` sourcing all info from file `frontmatter`
See here: https://develop-docs-revamp--substrate-docs.netlify.app/tutorials/
- [x]  simplified tutorial `frontmatter` template:
```yaml
---
title: Build a local blockchain
description: Launch and interact with your first Substrate chain in this minimal end-to-end guide.
featured_image: /media/images/docs/tutorials/build-blockchain/thumbnail.jpg
keywords:
  - node
  - template
  - basics
difficulty: 1 
duration: 60 #using integer in minutes
skills:
  - Rust
  - Blockchain basics
#providing links to next and prev page to be generated in the footer
previous: /main-docs/why-substrate/choose-a-dev-platform/
next: /reference/glossary/
---
```

## Media
- [x] media files to be stored (using verbose and complete internal path): `./media/images/docs/<path>/:image`
- [x] to be referenced in `.md` as: `/media/images/docs/tutorials/build-blockchain/thumbnail.jpg` 
- [x] add image resolver to work around `gatsby-relative-images` not parsing image source `relative paths`
- [x] add lazy loading to remote image sources
 
## Docs navigation
- [x] use single `yaml` config file (`./config/docs.yaml`) to generate docs sidebar navigation (reference Mkdocs)
```yaml
# Navigation:
nav:
  - Quick Start:
      - '/quick-start/'
  - Docs:
      - '/main-docs/' #category page link
      - 'Why Substrate?': '/main-docs/why-substrate/choose-a-dev-platform/' #page link
  - Reference:
      - 'Glossary': '/reference/glossary/'
  - Tutorials:
      - '/tutorials/'
      - 'Build a local blockchain': '/tutorials/build-blockchain/'
      - 'Initiate a Forkless Runtime Upgrade': '/tutorials/forkless-upgrades/'
```
- [x] accepts external URL instead of `path`
- [ ] update `yaml` file `nav:` structure (using `key/value` pairs) to support future `i18n`

## Infrastructure
- [ ] moving unused files into `__legacy` folder prior future deletion 
- [ ] upgrade `lunr` search to build index upon `.md` files
- [ ] upgrade gatsby version + plugin compatibility
- [ ] decommission `mdx` components and plugins

---

Great minds, haha. I also put together a list of "requirements" from the doc perspective. This looks closely aligned with what I had in mind.

For reference, here was my short list:

- [ ] Writer-controllable navigational structure that is easy to modify. It needs to be easy to:
    - Add new pages
    - Change the order of pages
    - Change the titles of pages and have any name changes picked up in navigation (if it is a manual step, it needs to be easy)
- [ ] Simple and flexible file structure that accommodates grouping multiple files in the same directory with human-readable file names.

- [ ] Full site search (ideally, controllable search indexing to skip some words, but that’s a nice-to-have).

- [ ] Simple versioning support (archive snapshots on some cadence is probably the simplest solution). Mkdocs supports a separate Python extension to provide some simple versioning if docs are hosted on GitHub pages. https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning
https://github.com/jimporter/mike

- [ ] Syntax highlighting (tabbed code fence blocks would be a nice-to-have, but so far I’m not seeing much that calls for that approach).

- [ ] Controllable copy to clipboard for code blocks, so that the copy button is not included for output or code examples that shouldn’t be copied exactly as-is.

- [ ] Very simple minimalistic Note, Warning, and Tip styles (could be just done with CSS instead of React components).
